#!/usr/bin/env bash
# Regression for sweep memory commits: address-comments memory notes created
# from a secondary git worktree ride that worktree's PR commit.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$DIR/../../.." && pwd)"
source "$ROOT/skills/woostack-init/scripts/tests/assert.sh"

RESOLVE="$DIR/resolve-root.sh"
MEMORY_RECORD="$DIR/memory-record.sh"

repo="$(mktemp -d)"
wt="$repo-worktree"
out="$(mktemp -d)"
repo="$(cd "$repo" && pwd -P)"
out="$(cd "$out" && pwd -P)"
wt="$(cd "$(dirname "$wt")" && pwd -P)/$(basename "$wt")"

git -C "$repo" init -q
git -C "$repo" config user.email test@example.com
git -C "$repo" config user.name "Test User"
printf 'root\n' > "$repo/README.md"
git -C "$repo" add README.md
git -C "$repo" commit -q -m init

mkdir -p "$repo/.woostack/memory"
cat > "$repo/.woostack/memory/MEMORY.md" <<'MD'
<!-- generated by build-index.sh — do not edit by hand -->

# Memory
MD

git -C "$repo" worktree add -q -b address-run "$wt" HEAD
wt="$(cd "$wt" && pwd -P)"

mkdir -p "$wt/.woostack/memory"

resolved="$out/roots.env"
(
  cd "$wt"
  env -u GITHUB_WORKSPACE bash -c 'source "$1"; printf "root=%s\ncommon=%s\n" "$WOOSTACK_ROOT" "$WOOSTACK_COMMON_ROOT"' _ "$RESOLVE"
) > "$resolved"

assert_eq "$(grep '^root=' "$resolved" | cut -d= -f2-)" "$wt" "WOOSTACK_ROOT stays on the active worktree"
assert_eq "$(grep '^common=' "$resolved" | cut -d= -f2-)" "$repo" "WOOSTACK_COMMON_ROOT resolves to primary checkout"

primary_before="$(find "$repo/.woostack/memory" -maxdepth 1 -type f -name '*.md' ! -name MEMORY.md | wc -l | tr -d ' ')"
worktree_before="$(find "$wt/.woostack/memory" -maxdepth 1 -type f -name '*.md' ! -name MEMORY.md | wc -l | tr -d ' ')"
(
  cd "$wt"
  env -u GITHUB_WORKSPACE \
    WOOSTACK_NOW=2026-06-17 \
    LEARNING='Worktree address-comments helpers write tracked memory to the active worktree.' \
    MEMORY_SCOPE='skills/**' \
    bash "$MEMORY_RECORD" > "$out/memory-record.out"
)
primary_after="$(find "$repo/.woostack/memory" -maxdepth 1 -type f -name '*.md' ! -name MEMORY.md | wc -l | tr -d ' ')"
worktree_after="$(find "$wt/.woostack/memory" -maxdepth 1 -type f -name '*.md' ! -name MEMORY.md | wc -l | tr -d ' ')"

assert_eq "$primary_after" "$primary_before" "address memory-record leaves primary memory notes unchanged"
assert_eq "$worktree_after" "$((worktree_before + 1))" "address memory-record writes scoped note to active worktree memory store"

rm -rf "$repo" "$wt" "$out"
finish
