#!/usr/bin/env bash
# Regression for issue #279: local-only memory and metrics live in the primary
# checkout, even when review helpers run from a secondary git worktree.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$DIR/../../.." && pwd)"
source "$ROOT/skills/woostack-init/scripts/tests/assert.sh"

RESOLVE="$DIR/resolve-root.sh"
MEMORY_RECORD="$DIR/memory-record.sh"
METRICS_FOLD="$DIR/metrics-fold.sh"

repo="$(mktemp -d)"
wt="$repo-worktree"
out="$(mktemp -d)"
repo="$(cd "$repo" && pwd -P)"
out="$(cd "$out" && pwd -P)"
wt="$(cd "$(dirname "$wt")" && pwd -P)/$(basename "$wt")"

git -C "$repo" init -q
git -C "$repo" config user.email test@example.com
git -C "$repo" config user.name "Test User"
printf 'root\n' > "$repo/README.md"
git -C "$repo" add README.md
git -C "$repo" commit -q -m init

mkdir -p "$repo/.woostack/memory"
cat > "$repo/.woostack/memory/MEMORY.md" <<'MD'
<!-- generated by build-index.sh — do not edit by hand -->

# Memory
MD
printf '.woostack/metrics.json\n' > "$repo/.gitignore"

git -C "$repo" worktree add -q -b worktree-run "$wt" HEAD
wt="$(cd "$wt" && pwd -P)"

resolved="$out/roots.env"
(
  cd "$wt"
  env -u GITHUB_WORKSPACE bash -c 'source "$1"; printf "root=%s\ncommon=%s\n" "$WOOSTACK_ROOT" "$WOOSTACK_COMMON_ROOT"' _ "$RESOLVE"
) > "$resolved"

assert_eq "$(grep '^root=' "$resolved" | cut -d= -f2-)" "$wt" "WOOSTACK_ROOT stays on the active worktree"
assert_eq "$(grep '^common=' "$resolved" | cut -d= -f2-)" "$repo" "WOOSTACK_COMMON_ROOT resolves to primary checkout"

before="$(find "$repo/.woostack/memory" -maxdepth 1 -type f -name '*.md' ! -name MEMORY.md | wc -l | tr -d ' ')"
(
  cd "$wt"
  env -u GITHUB_WORKSPACE \
    WOOSTACK_NOW=2026-06-17 \
    LEARNING='Worktree review helpers use primary local memory.' \
    MEMORY_SCOPE='skills/**' \
    bash "$MEMORY_RECORD" > "$out/memory-record.out"
)
after="$(find "$repo/.woostack/memory" -maxdepth 1 -type f -name '*.md' ! -name MEMORY.md | wc -l | tr -d ' ')"

assert_eq "$after" "$((before + 1))" "memory-record writes scoped note to primary memory store"
assert_exit 1 "$([ -d "$wt/.woostack/memory" ]; echo $?)" "memory-record does not create secondary worktree memory store"

mkdir -p "$out/review"
printf '{"metrics":true}\n' > "$out/review/config.json"
cat > "$out/review/findings.metrics.json" <<'JSON'
{
  "schema_version": 3,
  "mode": "defender-only",
  "degraded": false,
  "bugs": {
    "raw_count": 1,
    "nit_count": 0,
    "kept_count": 1,
    "dropped_by_defender": 0,
    "severity": {"HIGH": 1, "MEDIUM": 0, "LOW": 0}
  }
}
JSON

(
  cd "$wt"
  env -u GITHUB_WORKSPACE OUTDIR="$out/review" bash "$METRICS_FOLD" > "$out/metrics-fold.out"
)

assert_exit 0 "$([ -f "$repo/.woostack/metrics.json" ]; echo $?)" "metrics-fold writes primary metrics aggregate"
assert_exit 1 "$([ -f "$wt/.woostack/metrics.json" ]; echo $?)" "metrics-fold does not write metrics in secondary worktree"
assert_eq "$(jq -r '.runs' "$repo/.woostack/metrics.json")" "1" "primary metrics aggregate records run"

rm -rf "$repo" "$wt" "$out"
finish
