#!/usr/bin/env bash
# build-index.sh — regenerate <memdir>/MEMORY.md from note frontmatter.
# Indexes the dir only; never reads/writes the flat memory.md. Idempotent.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

MEM_DIR="${1:-.woostack/memory}"
INDEX="$MEM_DIR/MEMORY.md"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
shopt -s nullglob
for f in "$MEM_DIR"/*.md; do
  base="$(basename "$f")"
  [ "$base" = "MEMORY.md" ] && continue
  name="$(field "$f" name)"; type="$(field "$f" type)"
  scope="$(field "$f" scope || true)"; hook="$(field "$f" hook || true)"
  [ -z "$hook" ] && hook="$(first_body_line "$f")"
  first_scope="$(printf '%s' "$scope" | cut -d',' -f1 | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
  [ -z "$first_scope" ] && first_scope='*'
  hook="$(printf '%s' "$hook" | cut -c1-80)"
  printf '%s\t%s\t- [%s](%s) `%s` scope=`%s` — %s\n' \
    "$type" "$name" "$name" "$base" "$type" "$first_scope" "$hook" >> "$tmp"
done

{
  echo "<!-- generated by build-index.sh — do not edit by hand -->"
  echo
  LC_ALL=C sort -t"$(printf '\t')" -k1,1 -k2,2 "$tmp" | cut -f3-
} > "$INDEX"
rm -f "$tmp"
