#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$DIR/tests/assert.sh"
BI="$DIR/build-index.sh"

d="$(mk_memdir)"
# Out of alphabetical/type order on purpose.
mk_note "$d" zeta.md $'name: zeta\ntype: pattern\nscope: apps/web/**\nhook: zeta hook' 'body z'
mk_note "$d" alpha.md $'name: alpha\ntype: decision' $'First real line of alpha.\nmore'
mk_note "$d" beta.md $'name: beta\ntype: decision\nscope: a/**, b/**' 'body b'

bash "$BI" "$d"
idx="$(cat "$d/MEMORY.md")"

assert_contains "$idx" "- [alpha](alpha.md) \`decision\` scope=\`*\` — First real line of alpha." "alpha line w/ body-line hook + global scope"
assert_contains "$idx" "- [beta](beta.md) \`decision\` scope=\`a/**\`" "beta uses first scope glob"
assert_contains "$idx" "- [zeta](zeta.md) \`pattern\` scope=\`apps/web/**\` — zeta hook" "zeta uses hook field"

# sorted: decisions (alpha, beta) before pattern (zeta); alpha before beta
a=$(printf '%s\n' "$idx" | grep -n 'alpha' | cut -d: -f1)
b=$(printf '%s\n' "$idx" | grep -n 'beta'  | cut -d: -f1)
z=$(printf '%s\n' "$idx" | grep -n 'zeta'  | cut -d: -f1)
[ "$a" -lt "$b" ] && [ "$b" -lt "$z" ] && PASS=$((PASS+1)) || { FAIL=$((FAIL+1)); echo "  FAIL: sort order a<b<z ($a,$b,$z)"; }

# idempotent
cp "$d/MEMORY.md" "$d/.first"
bash "$BI" "$d"
assert_eq "$(cat "$d/MEMORY.md")" "$(cat "$d/.first")" "idempotent rebuild"

# flat memory.md is never touched by build-index
flat="$d/../memory.md"
echo "- flat bullet" > "$flat"
bash "$BI" "$d"
assert_not_contains "$(cat "$flat")" "alpha" "flat memory.md not touched"
rm -rf "$d" "$flat"

# empty dir -> header-only index, zero note lines
empty="$(mk_memdir)"
bash "$BI" "$empty"
assert_contains "$(cat "$empty/MEMORY.md")" "generated by build-index.sh" "empty dir -> header still written"
assert_eq "$(grep -c '^- \[' "$empty/MEMORY.md" || true)" "0" "empty dir -> no note lines"
rm -rf "$empty"

finish
