#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$DIR/tests/assert.sh"
BI="$DIR/build-index.sh"

d="$(mk_memdir)"
# Out of alphabetical/type order on purpose.
mk_note "$d" zeta.md $'name: zeta\ntype: pattern\nscope: apps/web/**\nhook: zeta hook' 'body z'
mk_note "$d" alpha.md $'name: alpha\ntype: decision' $'First real line of alpha.\nmore'
mk_note "$d" beta.md $'name: beta\ntype: decision\nscope: a/**, b/**' 'body b'
long_hook="this hook deliberately stays longer than eighty characters so the generated index remains accurate"
mk_note "$d" gamma.md "name: gamma
type: decision
scope: c/**, d/**
hook: $long_hook" 'body g'

bash "$BI" "$d"
idx="$(cat "$d/MEMORY.md")"

assert_contains "$idx" "- [alpha](alpha.md) \`decision\` scope=\`*\` — First real line of alpha." "alpha line w/ body-line hook + global scope"
assert_contains "$idx" "- [beta](beta.md) \`decision\` scope=\`a/**,b/**\`" "beta keeps all scope globs"
assert_contains "$idx" "- [gamma](gamma.md) \`decision\` scope=\`c/**,d/**\` — $long_hook" "gamma keeps full hook text"
assert_contains "$idx" "- [zeta](zeta.md) \`pattern\` scope=\`apps/web/**\` — zeta hook" "zeta uses hook field"

# sorted: decisions (alpha, beta) before pattern (zeta); alpha before beta
a=$(printf '%s\n' "$idx" | grep -n 'alpha' | cut -d: -f1)
b=$(printf '%s\n' "$idx" | grep -n 'beta'  | cut -d: -f1)
z=$(printf '%s\n' "$idx" | grep -n 'zeta'  | cut -d: -f1)
[ "$a" -lt "$b" ] && [ "$b" -lt "$z" ] && PASS=$((PASS+1)) || { FAIL=$((FAIL+1)); echo "  FAIL: sort order a<b<z ($a,$b,$z)"; }

# idempotent
cp "$d/MEMORY.md" "$d/.first"
bash "$BI" "$d"
assert_eq "$(cat "$d/MEMORY.md")" "$(cat "$d/.first")" "idempotent rebuild"

# unrelated legacy file is never touched by build-index
flat="$d/../memory.md"
echo "- flat bullet" > "$flat"
bash "$BI" "$d"
assert_not_contains "$(cat "$flat")" "alpha" "legacy file not touched"
rm -rf "$d" "$flat"

# empty dir -> header-only index, zero note lines
empty="$(mk_memdir)"
bash "$BI" "$empty"
assert_contains "$(cat "$empty/MEMORY.md")" "generated by build-index.sh" "empty dir -> header still written"
assert_eq "$(grep -c '^- \[' "$empty/MEMORY.md" || true)" "0" "empty dir -> no note lines"
rm -rf "$empty"

# AC3 (dream-wisdom): a sibling .woostack/wisdom/ store is structurally invisible to
# build-index (it globs only its own memdir), so a type: wisdom file must never leak
# into MEMORY.md.
wd="$(mk_memdir)"
mk_note "$wd" real.md $'name: real\ntype: decision' 'real memory note'
mkdir -p "$wd/../wisdom"
printf -- '---\nname: wis-leak\ntype: wisdom\n---\nGeneralized finding.\n' > "$wd/../wisdom/wis-leak.md"
bash "$BI" "$wd"
assert_contains "$(cat "$wd/MEMORY.md")" "real" "memory note is indexed"
assert_not_contains "$(cat "$wd/MEMORY.md")" "wis-leak" "sibling wisdom/ never leaks into MEMORY.md"
rm -rf "$wd" "$wd/../wisdom"

finish
